### ISSUE TITLE
Class role does not exist

### ISSUE THREAD

**Issue by sunthree74** [jeremykenedy/laravel-logger#20]
Why i have exception like this "Class role does not exist" when i want to acces route /activity?

**Comment by ahph37** [comment]
Why i have exception like this
 "Class App\Http\Controllers\jeremykenedy\LaravelLogger\App\Http\Controllers\LaravelLoggerController does not exist"
 when i want to acces route /activity?
 @jeremykenedy

**Comment by jeremykenedy** [comment]
Are you using the built-in routes or attempting to call them manually from web.php?

**Comment by ahph37** [comment]
Thanks for solving this problem
But now I have this problem that wasn't solved with the above solution
"Class role does not exist"
I manually created the role for my site,
Is there a way to get the role out of the way in order to avoid this problem?
@jeremykenedy

**Comment by jeremykenedy** [comment]
To diable middleware put: `LARAVEL_LOGGER_ROLES_ENABLED=false` in your .env

Or to use it and your own middleware of choice put the following in your `.env`
```
LARAVEL_LOGGER_ROLES_ENABLED=false
LARAVEL_LOGGER_ROLES_MIDDLWARE=role:admin // Change with the middlware you want.

All options are located here: https://github.com/jeremykenedy/laravel-logger#environment-file

**Comment by ahph37** [comment]
Thank you for your response
But now I have this problem
`Class 'Locale' not found
` 
@jeremykenedy

**Comment by jeremykenedy** [comment]
Missing a php library https://www.php.net/manual/en/book.intl.php

How to solve:
https://stackoverflow.com/questions/26153837/class-locale-not-found-issue-on-cakephp-3

Change `php5-intl` to what version of php you are when installing.

**Comment by ahph37** [comment]
Thank you for your response
I solved this problem with your help
But now I have this problem





![1](https://user-images.githubusercontent.com/40833900/77708749-915a5900-6fe6-11ea-931d-dca79f97fb97.png)
![Screenshot (92)](https://user-images.githubusercontent.com/40833900/77708776-a33bfc00-6fe6-11ea-82f5-d2ffb21b5e69.png)
@jeremykenedy

**Comment by jeremykenedy** [comment]
White screens have no hints. Check your error log `laravel.log` file

**Comment by ahph37** [comment]
`[2020-03-27 05:20:14] local.ERROR: Class App\Http\Controllers\LaravelLoggerController does not exist {"exception":"[object] (ReflectionException(code: -1): Class App\\Http\\Controllers\\LaravelLoggerController does not exist at D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:788)`
[stacktrace]
#0 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(788): ReflectionClass->__construct('App\\\\Http\\\\Contro...')
#1 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(667): Illuminate\\Container\\Container->build('App\\\\Http\\\\Contro...')
#2 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(615): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Contro...', Array)
#3 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(767): Illuminate\\Container\\Container->make('App\\\\Http\\\\Contro...', Array)
#4 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(233): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Contro...')
#5 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(833): Illuminate\\Routing\\Route->getController()
#6 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(794): Illuminate\\Routing\\Route->controllerMiddleware()
#7 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(693): Illuminate\\Routing\\Route->gatherMiddleware()
#8 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(673): Illuminate\\Routing\\Router->gatherRouteMiddleware(Object(Illuminate\\Routing\\Route))
#9 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#10 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#11 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#12 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#13 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#14 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 D:\\xampp\\htdocs\\blog1\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#31 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#32 D:\\xampp\\htdocs\\blog1\\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#33 D:\\xampp\\htdocs\\blog1\\server.php(21): require_once('D:\\\\xampp\\\\htdocs...')
#34 {main}
"}

**Comment by ahph37** [comment]
`[2020-03-27 05:20:14] local.ERROR: Class App\Http\Controllers\LaravelLoggerController does not exist {"exception":"[object] (ReflectionException(code: -1): Class App\\Http\\Controllers\\LaravelLoggerController does not exist at D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:788)`
@jeremykenedy
[stacktrace]
#0 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(788): ReflectionClass->__construct('App\\\\Http\\\\Contro...')
#1 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(667): Illuminate\\Container\\Container->build('App\\\\Http\\\\Contro...')
#2 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(615): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Contro...', Array)
#3 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(767): Illuminate\\Container\\Container->make('App\\\\Http\\\\Contro...', Array)
#4 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(233): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Contro...')
#5 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(833): Illuminate\\Routing\\Route->getController()
#6 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(794): Illuminate\\Routing\\Route->controllerMiddleware()
#7 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(693): Illuminate\\Routing\\Route->gatherMiddleware()
#8 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(673): Illuminate\\Routing\\Router->gatherRouteMiddleware(Object(Illuminate\\Routing\\Route))
#9 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#10 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#11 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#12 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#13 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#14 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 D:\\xampp\\htdocs\\blog1\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#31 D:\\xampp\\htdocs\\blog1\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#32 D:\\xampp\\htdocs\\blog1\\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#33 D:\\xampp\\htdocs\\blog1\\server.php(21): require_once('D:\\\\xampp\\\\htdocs...')
#34 {main}
"}

**Comment by jeremykenedy** [comment]
`App\Http\Controllers\LaravelLoggerController` does not exists. 

You have to use the built-in routes and connect redeclare them in your own routes or change the namespace.

See File: https://github.com/jeremykenedy/laravel-logger/blob/master/src/routes/web.php

**Comment by ahph37** [comment]
Thank you for your response

That's exactly the problem with the folder name and namespace !
folder name= `laravel-logger/src/`app/Http/Controllers/
but
namespace =jeremykenedy\`LaravelLogge`r\App\Http\Controllers
please, guide me
@jeremykenedy

![Screenshot (95)](https://user-images.githubusercontent.com/40833900/77710569-0d0ad480-6fec-11ea-91d2-380fda78ae84.png)

**Comment by jeremykenedy** [comment]
Did you follow the installation and usage instructions here:

https://github.com/jeremykenedy/laravel-logger#laravel-installation-instructions

https://github.com/jeremykenedy/laravel-logger#usage

**Comment by ahph37** [comment]
Yes, I followed all of Har's instructions
But now I got into trouble
Can you help me out?
@jeremykenedy
This is the database table where all the information is stored
![Screenshot (96)](https://user-images.githubusercontent.com/40833900/77711355-5f4cf500-6fee-11ea-85b4-e572fbf96fde.png)
